version: '3'
services:
  app:
    logging: {driver: "json-file", options: {max-size: "1m", max-file: "3"}}
    build:
      context: ./be_cherrypy
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./be_cherrypy:/app:ro
#    environment:
#      - VARIABLE=value
    restart: always

  nginx:
    logging: {driver: "json-file", options: {max-size: "1m", max-file: "3"}}
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/var/www/static:ro
    restart: always
