version: '3'
services:
  app:
    logging: {driver: "json-file", options: {max-size: "1m", max-file: "3"}}
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app:ro
#    environment:
#      - VARIABLE=value
    restart: always
